### ISSUE TITLE
Latest Update Messes Up Character Selection

### ISSUE THREAD

**Issue by smalllbuddy** [KingEnderBrine/-RoR2-ScrollableLobbyUI#7] opened 2024-04-09 05:25 UTC
The RealerCheatsUnlocks mod allows you to right click any survivor in the selection screen to unlock them. These mods have always been compatible, however since the latest update it no longer works on some pages. If you adjust your setting so that the CharacterPageArrowsInLine is set to false and CharacterSelectRows is set to 4, then these mods will work together, but this is the ONLY way.

**Comment by KingEnderBrine** [comment] 2024-04-09 10:08
Need more information. Did a quick test and it work fine wind 2 rows and even inline arrows. You can send a log (after you reproduced the error) and maybe you mod profile (as a file, since the code expires)

**Comment by smalllbuddy** [comment] 2024-04-09 16:35
Okay, fair warning I have 123 mods. Mostly character/map/item/api mods. I have few UI mods. I have troubleshooted disabling BetterUI, to no avail.
[MyProfile.zip](https://github.com/KingEnderBrine/-RoR2-ScrollableLobbyUI/files/14921482/MyProfile.zip)
[LogOutput.log](https://github.com/KingEnderBrine/-RoR2-ScrollableLobbyUI/files/14921503/LogOutput.log)

Edit - Here is a short clip showing what happens: [ReproducedError.zip](https://github.com/KingEnderBrine/-RoR2-ScrollableLobbyUI/files/14921544/ReproducedError.zip)

**Comment by KingEnderBrine** [comment] 2024-04-10 06:12
I don't think they ever been compatible from looking at RealerCheatUnlocks code and testing several older ScrollableLobbyUI version. It only works correctly on the first page, every other page copies respective unlocks from the first page. In the reproduction video when you click on sonic (14th character on that page excluding arrow button) it unlocks nemesis mercenary (?)  (who is also 14th on his page).
It's an issue that can only be fixed on RealerCheatUnlocks side.

**Comment by smalllbuddy** [comment] 2024-04-11 01:52
Ok, thank you for your help!

**Closed as completed** 2024-04-13 11:13 UTC
